name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/workflows/composite

      - name: Lint
        run: pnpm nx run-many -t lint --no-tui

      - name: Test
        run: pnpm nx run-many -t test --no-tui

      - name: Build
        run: pnpm nx run-many -t build --no-tui

      - name: Build docs
        run: pnpm nx run docs:build --no-tui
